// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mekkmtqqxnfituexacoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1la2ttdHFxeG5maXR1ZXhhY29pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MjY3MjAsImV4cCI6MjA3MTIwMjcyMH0.VNQdbQpcHncYO5BKEUNuz4j09zIQsxDLGWmlGUbpZug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});