// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gtupuqdengqiutgipeik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0dXB1cWRlbmdxaXV0Z2lwZWlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MDUwOTYsImV4cCI6MjA2MDQ4MTA5Nn0.YtnBlNT1ElntzY7LlNhaNqZPsTVx-ZZBpUNzRGgWfEU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});